repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.20
  hooks:
    # Common package
    - id: uv-lock
      name: uv-lock-common
      files: ^packages/green_fashion/
      args: [--project, packages/green_fashion]

    # API service
    - id: uv-lock
      name: uv-lock-api
      files: ^services/api/
      args: [--project, services/api]

    # ML API service
    - id: uv-lock
      name: uv-lock-ml-api
      files: ^services/ml-api/
      args: [--project, services/ml-api]
- repo: local
  hooks:
    - id: vite-build-check
      name: Check Vite build
      entry: bash -c "cd webapp && PATH=$PATH npm run build"
      language: system
      pass_filenames: false
      files: ^webapp/.*\.(js|jsx|ts|tsx|vue|css|scss|json)$
    - id: vite-type-check
      name: TypeScript type check
      entry: bash -c "cd webapp && PATH=$PATH npx tsc --noEmit"
      language: system
      pass_filenames: false
      files: ^webapp/.*\.(ts|tsx)$
      require_serial: true
