[project]
name = "green-fashion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "make>=0.1.6.post2",
    "matplotlib>=3.10.3",
    "pillow>=11.3.0",
    "scikit-learn>=1.7.0",
    "streamlit>=1.46.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "watchdog>=6.0.0",
]
