[project]
name = "green-fashion"
version = "0.1.0"
description = "Green Fashion core package for wardrobe management"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.8.0",
    "numpy>=1.24.0",
    "streamlit>=1.28.0",
    "pillow>=10.0.0",
    "scikit-learn>=1.3.0",
    "pymongo>=4.5.0",
    "google-cloud-storage>=2.10.0",
    "llvmlite>=0.44.0",
    "numba>=0.61.2",
    "rembg>=2.0.67",
    "onnxruntime>=1.22.1",
    "loguru>=0.7.3",
    "sqlalchemy>=2.0.0",
    "pymysql>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["green_fashion"]

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
]
