[project]
name = "green-fashion"
version = "0.1.0"
description = "Green Fashion core package for wardrobe management"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.8.0",
    "numpy>=1.24.0",
    "streamlit>=1.28.0",
    "pillow>=10.0.0",
    "scikit-learn>=1.3.0",
    "pymongo>=4.5.0",
    "google-cloud-storage>=2.10.0",
    # Observability dependencies
    # "structlog>=23.1.0",
    # "prometheus-client>=0.19.0",
    # "opentelemetry-api>=1.21.0",
    # "opentelemetry-sdk>=1.21.0",
    # "opentelemetry-instrumentation>=0.42b0",
    # "opentelemetry-instrumentation-fastapi>=0.42b0",
    # "opentelemetry-instrumentation-requests>=0.42b0",
    # "opentelemetry-instrumentation-pymongo>=0.42b0",
    # "opentelemetry-exporter-jaeger-thrift>=1.21.0",
    # "opentelemetry-exporter-prometheus>=1.12.0rc1",
    # "pydantic>=2.0.0",
    # "python-json-logger>=2.0.7",
    # "aiohttp>=3.9.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["green_fashion"]

[tool.uv]
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "isort>=5.12.0",
    "mypy>=1.5.0",
]
