name: Deploy to Development (Deprecated)

# ⚠️ DEPRECATED: This workflow has been replaced by separate workflows:
# - build-and-push.yml: Builds and pushes Docker images
# - deploy-infrastructure.yml: Deploys infrastructure changes
#
# Use those workflows instead of this one.

on:
  workflow_dispatch:
    inputs:
      notice:
        description: 'This workflow is deprecated - use build-and-push.yml and deploy-infrastructure.yml instead'
        required: false
        default: 'acknowledged'

jobs:
  deprecation-notice:
    runs-on: ubuntu-latest
    steps:
    - name: Deprecated workflow notice
      run: |
        echo "⚠️ This workflow is DEPRECATED"
        echo ""
        echo "Please use the new separated workflows:"
        echo "1. build-and-push.yml - Builds and pushes Docker images when code changes"
        echo "2. deploy-infrastructure.yml - Deploys infrastructure when Terraform changes"
        echo ""
        echo "Benefits of the new approach:"
        echo "✅ Faster builds - only rebuild when code changes"
        echo "✅ Independent deployments - deploy infrastructure without rebuilding"
        echo "✅ Better caching and efficiency"
        echo "✅ Path-based triggers for precise control"

        exit 1
